# Generated by Django 3.1.7 on 2022-12-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('profile', models.ImageField(upload_to='pics')),
                ('make', models.CharField(max_length=25)),
                ('year', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=50)),
                ('suspension', models.CharField(max_length=50)),
                ('baseprice', models.IntegerField()),
                ('currentprice', models.IntegerField()),
                ('buyitnow', models.IntegerField()),
                ('status', models.CharField(max_length=25, null=True)),
                ('sold', models.CharField(default='unsold', max_length=10)),
                ('start_date',  models.CharField(max_length=30)),
                ('highest_bidder', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
