# Generated by Django 3.1.7 on 2023-01-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carDealer', '0002_auto_20230101_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('baseprice', models.IntegerField()),
                ('currentprice', models.IntegerField()),
                ('make', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
            ],
        ),
    ]
