# Generated by Django 3.1.7 on 2023-01-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carDealer', '0003_biddetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
