# Generated by Django 3.1.7 on 2023-01-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carDealer', '0004_admin_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='makedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=100)),
                ('urlresized', models.CharField(max_length=100)),
            ],
        ),
    ]
