# Generated by Django 3.1.7 on 2023-01-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carDealer', '0006_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AlterField(
            model_name='item',
            name='currentprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
